name: Demo Workflow

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            -main
            - dev
    # schedule:
    #     # - cron: "*/1 * * * *"             

jobs:
    setup_job:
       runs-on: ubuntu-latest # mac-os-latest, windows-latest
       steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: create file
          run: |
            touch github-action32.txt
            ls -la
             echo "Hello World"
             cat README.md
         
    build_job:
        needs: 
         - setup_job
        runs-on: windows-latest
        steps: 
            - name: display hello
              run: echo hello 
            - name: display github-action32.txt
              run: cat github-action32.txt

       
    deploy_job:
        needs: build_job
        runs-on: macos-latest
        steps:
            - run: echo hello mac
       


